### ISSUE TITLE
Create Projects Board for NorKorr

### ISSUE THREAD

**Issue by arockenberger** [arockenberger/NorKorr#29]
How to guide can be found here: (https://help.github.com/articles/about-project-boards/)

Project management tool integrated in GitHub. I think it is worth a try. Read the guide above and tell me what you think about it!

**Comment by hildeboee** [comment]
I have tried using kanban for keeping track of my own tasks at work, but I never got into it and after a while I forgot checking it and when back to my old habits.

Perhaps it is easier to use project boards when we are several people and can use it to keep track of the work of others as well as one's own tasks and of the overall project progress? And perhaps our tasks here are smaller and doesn't last for months and years? I'm not sure about how this will work, but I'm willing to try.

**Comment by arockenberger** [comment]
I've been reading up on using Kanban for project management; it seems most suited for task management that doesn't have to deal with too long time periods (so much for humanities projects). But I think we can make it work! :)

**Comment by arockenberger** [comment]
Done! Look under Projects. Please don't be afraid of moving stuff around, adding tasks etc.
