### ISSUE TITLE
Rydde repositoriet

### ISSUE THREAD

**Issue by arockenberger** [arockenberger/NorKorr#3]
Rydde opp i repository:

- [x] Hoveddelen av README.md skal flyttes til Wiki
- [x] Referatet fra workshop Notes.md skal flyttes til workshop-mappe
- [ ] Deltagere lager en beskrivelse av sine korrespondanse-samlinger (muligens i Wiki'en)
- [x] CMIF XML-skjema kopieres til vårt repository
- [x] finne ut hva et repository heter på norsk…

**Comment by hildeboee** [comment]
Jeg har spurt Språkrådet hva de tror om lager eller arkiv for 'repository'
eller om de har andre forslag og melder tilbake når jeg hører fra dem. Den
direkte oversettelsen blir vel lager, og lagring er jo funksjonen til et
repository?

Den tir. 18. sep. 2018 kl. 13:27 skrev Annika Rockenberger <
notifications@github.com>:

**Comment by hildeboee** [comment]
Jeg forsøkte å lage et prosjekt, men syns ikke det ser ut som om formatet egner seg til å legge inn referatet fra workshopen. Mon tro om det ikke er bedre å legge det inn som ei side i wikien?

**Comment by arockenberger** [comment]
Ellers så lager vi en mappe med referater?!
Jeg har ikke ennå undersøkt prosjektforvaltningen ved GitHub – kanskje det er på tid?

**Comment by arockenberger** [comment]
[Youtube Video om GitHub Projects](https://www.youtube.com/watch?v=C6MGKHkNtxU)

**Comment by hildeboee** [comment]
Jeg ser ikke -- heller ikke fra videoen -- at man kan lage mapper. Det ser bare ut som om man kan lage tabeller med kolonner for å håndtere gjøremål/oppgaver, så jeg skjønner ikke helt hvor vi skulle legge referatet? :-)

**Comment by arockenberger** [comment]
Enkelst er å lage en mappe "referater" i repositoriet og flytte filen "Notes.md" til mappen!

**Comment by hildeboee** [comment]
Jeg har fått svar fra Språkrådet allerede: "Både repositorium og bank er i bruk i norsk, jf. Språkbanken. Ellers holder jeg med deg i at arkiv burde være dekkende i de fleste sammenhenger."
Så da kan vi jo gjøre et valg, kanskje? Repositorium, bank eller arkiv?

**Comment by arockenberger** [comment]
Jeg ville foretrekke "repositorium", da vet i hvert fall alle, hva menes og det ligner det internasjonale "repository" mest.

**Comment by arockenberger** [comment]
> Rydde opp i repository:
> 
> * Hoveddelen av README.md skal flyttes til Wiki
> * Referatet fra workshop Notes.md skal flyttes til workshop-mappe
> * Deltagere lager en beskrivelse av sine korrespondanse-samlinger (muligens i Wiki'en)
> * CMIF XML-skjema kopieres til vårt repository
> * finne ut hva et repository heter på norsk…

Update!

[x] Hoveddelen av README.md skal flyttes til Wiki
[x] Referatet fra workshop Notes.md skal flyttes til workshop-mappe
[x]CMIF XML-skjema kopieres til vårt repository
[x] finne ut hva et repository heter på norsk…
[ ] Deltagere lager en beskrivelse av sine korrespondanse-samlinger (muligens i Wiki'en)

Almost all done; there will be more, though! Keep adding to this thread!

@hildeboee @MetteWitting @ellenwiger

**Comment by arockenberger** [comment]
I have moved the contents from the wiki to the new repository, https://github.com/norkorr/project - closing the issue
