### ISSUE TITLE
Integrate Correspondence collections from Lokalhistoriewiki

### ISSUE THREAD

**Issue by arockenberger** [arockenberger/NorKorr#30]
https://lokalhistoriewiki.no/wiki/Kjeldearkiv:Liste_over_Norgesbrev
https://lokalhistoriewiki.no/wiki/Kategori:Brevsamling_Kleiven-Prestgard
https://lokalhistoriewiki.no/wiki/Kategori:Johan_Castbergs_brevsamling
https://lokalhistoriewiki.no/wiki/Kategori:Lesjabrev
https://lokalhistoriewiki.no/wiki/Kjeldearkiv:Amerikabrev_fra_Halstein_H._Fl%C3%B8se,_13._februar_1838
https://lokalhistoriewiki.no/wiki/Kategori:Brev

**Comment by arockenberger** [comment]
In the wiki, each letter is transcribed and in the header, metadata is encoded like this:
```
{{Infoboks brev
| målform       = nn
| bilde         = Heime og ute forside.jpg
| dato          = 14.2.1886
| sted          = [[Seljord]]
| fra           = [[Ivar Kleiven]]
| til           = [[Kristian Prestgard]]
| nummer        = 1
| samling       = [[Brevsamling Ivar Kleiven og Kristian Prestgard 1886–1932]]
| oppbevaring   = [[Opplandsarkivet Vågå]]
}}
```
We need to create a script that can harvest the metadata we are interested in from each file.
dato, sted, fra, til, samling
Either into a .csv or directly into a CMIF file. I prefer .csv.

**Comment by arockenberger** [comment]
@MarianneWiig has added a lot of info to our Wiki! Check the above list – is it complete? If so, let's move on and create CMIF files for the individual letters

**Comment by MarianneWiig** [comment]
@arockenberger The list is complete, but only Letters to and from Ivar Kleiven and Kristian Prestgard (NB) and Letters from Norway (NB) have metadata (info boxes) and not all the other letters are transcribed. We are in the process of checking out cmif/csv now!

**Comment by arockenberger** [comment]
Has been moved as new Issue to https://github.com/norkorr/lokalhistoriewiki/issues/1 - closing Issue here.
