### ISSUE TITLE
Upload Final Version of Paper

### ISSUE THREAD

**Issue by arockenberger** [arockenberger/NorKorr#31]
!! publication ready paper must be uploaded to DHN2019 ConfTool by Feb 10, 2019

**Comment by evelynthor** [comment]
Kommentar til tekst i paper. Rekkefølgen på oss (organisasjonene) nevnt under 1 About the Project sammenfaller ikke med rekkefølgen vi presenteres i under 1.2 Status Quo. Jeg synes den bør det. Hva synes dere?

**Comment by evelynthor** [comment]
Figur 5 bør flyttes og komme rett etter omtalen av Case 2 -letters to and from Norwegian Artist Edvard Munch.

**Comment by evelynthor** [comment]
Likedan bør figur 6 flyttes og komme etter teksten til Case 3- Correspondence Collection from the University Library at the Norwegian University of Science and Technology.

**Comment by arockenberger** [comment]
Det er alt rettet i den ferdige versjonen av paper som ble lastet opp for noen dager siden av @MarianneBergen 
https://github.com/arockenberger/NorKorr/blob/master/poster/submission_NorKorr_DHN2019/samplepaper.tex
