### ISSUE TITLE
Integrate Correspondence Editions from Bokselskap.no

### ISSUE THREAD

**Issue by arockenberger** [arockenberger/NorKorr#33]
All correspondence and letter editions published on bokselskap.no, published until Jan 2019.

Create CMIF, upload to CorrespSearch, store CMIF (and .csv) in [data](https://github.com/arockenberger/NorKorr/tree/master/data) folder.

**Comment by ellenwiger** [comment]
05.02.19: Created 7 CMIF files containing letter editions from bokselskap.no, sent them to CorrespSearch and stored them in the data folder (as well as on the Bokselskap server). Started working on some of the larger NSL-editions.

**Comment by arockenberger** [comment]
CorrespSearch has shared the new editions via Twitter and other social media; I tweeted it back at NB's official Twitter handle. Thank you so much, Ellen! Awesome job!

**Comment by arockenberger** [comment]
This is an ongoing task, closing the issue. See for new additions https://github.com/norkorr/bokselskap
